apiVersion: ignite.weave.works/v1alpha4
kind: VM
metadata:
  name: parrotos-novnc-vm3
spec:
  cpus: 2
  memory: 2GB
  image:
    oci: poridhi/parrotos-novnc:1.0.0
  kernel:
    oci: weaveworks/ignite-kernel:5.10.51